### ISSUE TITLE
useTranslation is being called way more than it should

### ISSUE THREAD

**Issue by ReactAcademyCa** [wojtekmaj/react-lifecycle-methods-diagram#55] opened 2019-11-14 05:28 UTC
useTranslation() gets called way too much. Between 350 and 450 times per screen. (it depends on the screen).  Because it updates the state in a useEffect(), it gets re-rendered and called a few times. 

It should be called way less often (below 35 times per screen). 
You can easily see this by placing a **console.log()** in the main body of the **useTranslation()** function.

**Comment by wojtekmaj** [comment] 2019-11-14 10:36
Reduced from 316 to 133 calls in default view via commits above. Most components are getting two updates: null (when language is not loaded yet) and with string (after language load). Other useTranslation calls are caused by other component updates.

**Comment by wojtekmaj** [comment] 2019-11-14 11:40
Closing as useTranslation is now fine; we can work on reducing needless updates in some components requesting translations.

**Closed by wojtekmaj** 2019-11-14 11:40 UTC
Labels: bug

**Comment by ReactAcademyCa** [comment] 2019-11-19 23:43
Thank you for the fix. This is a big improvement.
